SELECT W.CODE_DESCR Sector,COUNT(*),
--SUBSTR(A.AREA_CODE,1,3) Book, SUBSTR(A.AREA_CODE,4,2) BG,
--A.CUSTOMER_NUM||A.CONS_CHK_DIGIT Customer_No, 
--b.CUSTOMER_NAME CUSTOMER_NAME, 
--c.ADDR_DESCR1||', '||c.ADDR_DESCR2||'  '||c.ADDR_DESCR3 Address,  
         SUM(NVL(a.ENG_CHRG_SR,0)+NVL(a.ENG_CHRG_OFPK,0)+NVL(a.ENG_CHRG_PK,0)+NVL(a.PFC_CHARGE,0)+ 
        NVL(a.XF_LOSS_CHRG,0)+NVL(a.MINIMUM_CHRG,0)+nvl(a.XF_RENT,0)) UNIT_CHARGE,SUM(NVL(a.SERVICE_CHRG,0)) SEVICE,SUM(NVL(a.DEMAND_CHRG,0)) DEMAND, 
        --ROUND(NVL(a.ARR_ADV_ADJ_PRN,0)+NVL(A.ADJUSTED_PRN,0)) Arr_Prn,Round(NVL(a.ARR_ADV_ADJ_VAT,0)+NVL(A.ADJUSTED_VAT,0)) Arr_Vat,
        SUM(NVL(A.CURRENT_LPS,0)) LPS,SUM(NVL(A.CURRENT_VAT,0)) VAT
        --Round(NVL(a.ARR_ADV_ADJ_PRN,0)+NVL(A.ADJUSTED_PRN,0) +NVL(a.ARR_ADV_ADJ_VAT,0)+NVL(A.ADJUSTED_VAT,0)+NVL(a.ARR_ADV_ADJ_LPS,0)+NVL(A.CURRENT_LPS,0)+NVL(A.ADJUSTED_LPS,0)) Total_Arrear,
        --Round(NVL(Total_Bill,0)) Total_Bill 
FROM 
     BC_BILL_IMAGE A, 
     BC_CUSTOMERS b, 
     BC_CUSTOMER_ADDR c, 
     BC_LOCATION_MASTER d, 
     --BC_MONTHLY_LIKELY E, 
     BC_BUS_TYPE_CODE BT ,
     BC_CUSTOMER_OWNER_TYPE w,
     BC_MINISTRY_CODE Y,
     BC_CUSTOMER_TYPE_MST Z 
WHERE 
bill_cycle_code =:BC
AND A.CUST_ID = b.CUST_ID 
AND A.Location_Code=:Loc 
AND c.CUST_ID = b.CUST_ID 
--AND c.CUST_ID = E.CUST_ID 
and A.BUS_TYPE_CODE=BT.BUS_TYPE_CODE 
--AND E.EXP_DATE IS NULL 
AND A.LOCATION_CODE = d.LOCATION_CODE 
AND c.ADDR_TYPE = 'B' 
AND c.ADDR_EXP_DATE IS NULL 
AND SUBSTR(DECODE(LENGTH(A.CUST_STATUS),5,A.CUST_STATUS,'98715'),5,1)=W.CUSTOMER_OWNER_CODE
AND SUBSTR(DECODE(LENGTH(A.CUST_STATUS),5,A.CUST_STATUS,'98715'),1,2)=Y.MINISTRY_CODE
AND SUBSTR(DECODE(LENGTH(A.CUST_STATUS),5,A.CUST_STATUS,'98715'),3,2) = Z.CUSTOMER_TYPE_CODE
AND SUBSTR(DECODE(LENGTH(A.CUST_STATUS),5,A.CUST_STATUS,'98715'),5,1) in (1,2,3,4,5)  
--d NVL(a.ARR_ADV_ADJ_PRN,0)+NVL(A.ADJUSTED_PRN,0) +NVL(a.ARR_ADV_ADJ_VAT,0)+NVL(A.ADJUSTED_VAT,0)+NVL(a.ARR_ADV_ADJ_LPS,0)+NVL(A.CURRENT_LPS,0)+NVL(A.ADJUSTED_LPS,0)>10000
GROUP BY W.CODE_DESCR
ORDER BY 2 ASC
----------------------
SELECT SUM(NVL(advance,0)),COUNT(CUST_ID),bill_cycle_code FROM ebc.BC_meter_READING_CARD_DTL
WHERE cust_id IN(SELECT cust_id FROM ebc.bc_customer_meter
WHERE Check_pt_meter_iD IN(SELECT equip_id FROM ebc.bc_customer_meter WHERE cust_id IN(SELECT cust_id
FROM ebc.bc_customers WHERE customer_num=&CUSTOMER_NUM '3515239')))
AND bill_cycle_code IN('202009')--,'201207','201206','201205','201204','201203','201202','201201','201112')
GROUP BY bill_cycle_code
------------------
SELECT C.LOCATION_CODE LOCATION,C.AREA_CODE AREA,C.CUSTOMER_NUM CUSTOMER,C.CUSTOMER_NAME NAME,
A.ADDR_DESCR1||A.ADDR_DESCR2 ADDRESS,C.SPL_TYPE STYPE,M.EQUIP_ID MOTHER
FROM EBC.BC_CUSTOMERS C,EBC.BC_CUSTOMER_ADDR A,ebc.bc_customer_meter M
WHERE  A.CUST_ID=C.CUST_ID
AND M.CUST_ID=A.CUST_ID
AND C.CUSTOMER_NUM IN('2953977') ---=&CUST
AND C.LOCATION_CODE='F2'
AND C.SPL_TYPE IN ('CPR','CPV')
AND A.ADDR_TYPE='B'
--AND M.REPLACED_METER_ID IS NOT NULL
--AND M.REC_STATUS<>'U'
--ORDER BY M.EQUIP_ID
UNION 
SELECT C.LOCATION_CODE LOCATION,C.AREA_CODE AREA,C.CUSTOMER_NUM CUSTOMER,C.CUSTOMER_NAME NAME,
A.ADDR_DESCR1||A.ADDR_DESCR2 ADDRESS,C.SPL_TYPE STYPE,M.CHECK_PT_METER_ID MOTHER
FROM EBC.BC_CUSTOMERS C,ebc.bc_customer_meter M,EBC.BC_CUSTOMER_ADDR A
WHERE C.CUST_ID=M.CUST_ID
AND A.CUST_ID=C.CUST_ID
AND M.CHECK_PT_METER_ID IN (SELECT  EQUIP_ID FROM EBC.bc_customer_meter WHERE CUSTOMER_NUM IN('2953977'))
AND C.LOCATION_CODE='D8'
AND C.SPL_TYPE = 'CPC'	
AND A.ADDR_TYPE='B'

--- FIND CPR WITH CPC-   CPR EQUIP_ID= CPC CHECK_PT_METER_ID   -
SELECT A.LOCATION_CODE,A.AREA_CODE,A.CUSTOMER_NAME, A.CUSTOMER_NUM||A.CHECK_DIGIT CUSTOMER,B.METER_NUM,B.SPL_TYPE FROM EBC.BC_CUSTOMERS A,ebc.BC_CUSTOMER_METER B
WHERE A.CUSTOMER_NUM=B.CUSTOMER_NUM AND B.EQUIP_ID IN (SELECT CHECK_PT_METER_ID  FROM ebc.BC_CUSTOMER_METER 
WHERE CUSTOMER_NUM ='2953135')
